// styles.ts
import { StyleSheet, Platform } from 'react-native';

const fontFamily = Platform.select({
  ios: 'System',
  android: 'Roboto',
});

const fontWeights = {
  regular: Platform.select({ ios: '400', android: 'normal' }),
  medium: Platform.select({ ios: '500', android: '500' }),
  semibold: Platform.select({ ios: '600', android: '600' }),
  bold: Platform.select({ ios: '700', android: 'bold' }),
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: fontWeights.bold,
    marginBottom: 16,
    fontFamily: fontFamily,
  },
  premiumCard: {
    borderRadius: 20,
    padding: 24,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  heroSection: {
    borderRadius: 24,
    padding: 32,
    marginBottom: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 12,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: fontWeights.bold,
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
    fontFamily: fontFamily,
  },
  heroSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    fontWeight: fontWeights.medium,
    fontFamily: fontFamily,
  },
  termInputContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 0,
    marginTop: 0,
  },
  termInputWrapper: {
    flex: 1,
    position: 'relative',
  },
  termLabel: {
    position: 'absolute',
    right: 16,
    top: 16,
    fontSize: 14,
    fontWeight: '600',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: fontWeights.semibold,
    marginBottom: 8,
    fontFamily: fontFamily,
  },
  // Loan Term Compact Section - Updated
  loanTermSection: {
    marginBottom: 16,
  },
  loanTermLabel: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    fontFamily: fontFamily,
  },
  termInputBox: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    height: 52,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  termInput: {
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    height: 52,
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 17,
    fontWeight: '600',
    backgroundColor: 'transparent',
  },
  extraPaymentToggle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  extraPaymentToggleText: {
    fontSize: 18,
    fontWeight: fontWeights.semibold,
    fontFamily: fontFamily,
  },
  extraPaymentToggleIcon: {
    fontSize: 24,
    fontWeight: fontWeights.bold,
  },
  resultsContainer: {
    gap: 16,
  },
  resultRow: {
    flexDirection: 'row',
    gap: 12,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 20,
    padding: 24,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: fontWeights.bold,
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: fontFamily,
  },
  modalMessage: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: fontFamily,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  guidelinesCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    marginTop: 20,
  },
  guidelinesTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  guidelinesText: {
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '500',
  },
  loansList: {
    padding: 0,
  },
  loanCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  loanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  loanName: {
    fontSize: 20,
    fontWeight: fontWeights.bold,
    flex: 1,
    fontFamily: fontFamily,
  },
  deleteButton: {
    padding: 12,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loanDetails: {
    marginBottom: 16,
  },
  loanDetail: {
    fontSize: 15,
    marginBottom: 4,
    fontWeight: fontWeights.medium,
    fontFamily: fontFamily,
  },
  loanActions: {
    flexDirection: 'row',
    gap: 8,
  },
  viewButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  viewButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: fontWeights.bold,
    fontFamily: fontFamily,
    textAlign: 'center',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyStateText: {
    fontSize: 18,
    textAlign: 'center',
    lineHeight: 26,
    fontWeight: '500',
  },
  amortizationHeader: {
    padding: 20,
    borderBottomWidth: 1.5,
  },
  amortizationTitle: {
    fontSize: 22,
    fontWeight: fontWeights.bold,
    marginBottom: 8,
    fontFamily: fontFamily,
  },
  amortizationSubtitle: {
    fontSize: 16,
    fontWeight: fontWeights.medium,
    marginBottom: 16,
    fontFamily: fontFamily,
  },
  activeScenarioText: {
    fontSize: 14,
    fontWeight: fontWeights.semibold,
    marginTop: 8,
    fontFamily: fontFamily,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  actionBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
  },
  actionBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: fontWeights.semibold,
    fontFamily: fontFamily,
  },
  // Updated Action Button Styles for Icons
  actionBtnImproved: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
    minHeight: 64,
    flexDirection: 'column',
    gap: 4,
  },
  actionBtnTextImproved: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  // Icon text styles for action buttons
  actionBtnIconText: {
    fontSize: 18,
    marginBottom: 4,
  },
  scenariosContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    maxHeight: 120,
  },
  scenarioCardContainer: {
    position: 'relative',
    marginRight: 12,
  },
  scenarioCard: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    minWidth: 140,
    maxWidth: 160,
  },
  scenarioName: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  scenarioDetails: {
    fontSize: 12,
    lineHeight: 16,
  },
  deleteScenarioBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteScenarioBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 20,
  },
  amortizationTableHeader: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  amortizationHeaderCell: {
    flex: 1,
    fontSize: 13,
    fontWeight: fontWeights.bold,
    color: '#ffffff',
    textAlign: 'center',
    fontFamily: fontFamily,
  },
  monthCell: {
    flex: 0.6,
  },
  amortizationTable: {
    flex: 1,
  },
  amortizationRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
  },
  amortizationCell: {
    flex: 1,
    fontSize: 13,
    textAlign: 'center',
    fontWeight: fontWeights.semibold,
    fontFamily: fontFamily,
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  settingLabelContainer: {
    flex: 1,
    marginRight: 16,
  },
  settingLabel: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  settingDescription: {
    fontSize: 14,
    fontWeight: '500',
  },
  settingValue: {
    fontSize: 16,
    fontWeight: '700',
  },
  aboutCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    marginTop: 16,
  },
  aboutTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 6,
  },
  aboutVersion: {
    fontSize: 15,
    marginBottom: 8,
    fontWeight: fontWeights.semibold,
    fontFamily: fontFamily,
  },
  aboutBuilt: {
    fontSize: 14,
    marginBottom: 12,
    fontWeight: fontWeights.semibold,
    fontFamily: fontFamily,
    fontStyle: 'italic',
  },
  aboutDescription: {
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 16,
    fontWeight: '500',
  },
  aboutFeatures: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  currencyList: {
    maxHeight: 300,
  },
  currencyOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  currencyName: {
    fontSize: 16,
    fontWeight: '500',
  },
  currencySelected: {
    fontSize: 18,
    fontWeight: '700',
  },
  passcodeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  passcodeHeader: {
    alignItems: 'center',
    marginBottom: 60,
  },
  passcodeTitle: {
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  passcodeSubtitle: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  passcodeDisplay: {
    flexDirection: 'row',
    marginBottom: 80,
    justifyContent: 'center',
    gap: 16,
  },
  passcodeDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
  },
  passcodeKeypad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: 320,
    gap: 16,
  },
  passcodeKey: {
    width: 84,
    height: 84,
    borderRadius: 42,
    justifyContent: 'center',
    alignItems: 'center',
  },
  passcodeKeyText: {
    fontSize: 20,
    fontWeight: '400',
  },
  // Splash Screen Styles
  splashContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 80,
  },
  logoCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  logoIcon: {
    fontSize: 48,
  },
  splashTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  splashSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    fontWeight: '500',
  },
  splashFooter: {
    position: 'absolute',
    bottom: 80,
  },
  loadingDots: {
    flexDirection: 'row',
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },
  dot1: {
    transform: [{ scale: 1.2 }],
  },
  dot2: {
    transform: [{ scale: 1.0 }],
  },
  dot3: {
    transform: [{ scale: 0.8 }],
  },
  // Improved Amortization Styles
  amortizationRowImproved: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  monthColumn: {
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  monthNumber: {
    fontSize: 18,
    fontWeight: '700',
  },
  amortizationDataColumn: {
    flex: 1,
    gap: 8,
  },
  amortizationDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amortizationLabel: {
    fontSize: 14,
    fontWeight: '500',
  },
  amortizationValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  amortizationValueLarge: {
    fontSize: 16,
    fontWeight: '700',
  },
  // Improved Scenario Styles
  scenariosSection: {
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  scenariosTitle: {
    fontSize: 18,
    fontWeight: '700',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  scenarioCardImproved: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    marginRight: 12,
    minWidth: 180,
    maxWidth: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scenarioHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  scenarioNameImproved: {
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
  },
  newBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 8,
  },
  newBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
  },
  scenarioDetailsImproved: {
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  scenarioBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  scenarioBadgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  // Scenario Dropdown Styles
  scenarioDropdownSection: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scenarioDropdownTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scenarioDropdownLabel: {
    fontSize: 16,
    fontWeight: fontWeights.semibold,
    flex: 1,
    fontFamily: fontFamily,
  },
  scenarioDropdownIcon: {
    fontSize: 16,
    fontWeight: fontWeights.bold,
  },
  scenarioDropdownContent: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  scenarioDropdownItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scenarioDropdownItem: {
    flex: 1,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  scenarioDropdownItemText: {
    fontSize: 16,
    fontWeight: fontWeights.semibold,
    marginBottom: 4,
    fontFamily: fontFamily,
  },
  scenarioDropdownItemDetails: {
    fontSize: 14,
    fontWeight: fontWeights.medium,
    fontFamily: fontFamily,
  },
  scenarioDeleteBtn: {
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scenarioDeleteIcon: {
    fontSize: 18,
  },
  // Prepayment History Styles
  headerSection: {
    padding: 20,
    borderBottomWidth: 1,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 16,
    fontWeight: '500',
  },
  historyList: {
    padding: 16,
  },
  historyCard: {
    padding: 20,
    borderRadius: 16,
    borderWidth: 1.5,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  historyScenarioName: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  historyLoanName: {
    fontSize: 14,
    fontWeight: '500',
  },
  historyDeleteButton: {
    padding: 8,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteText: {
    fontSize: 14,
    fontWeight: '600',
  },
  historyDetails: {
    gap: 8,
    marginBottom: 16,
  },
  historyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyLabel: {
    fontSize: 14,
    fontWeight: '500',
  },
  historyValue: {
    fontSize: 14,
    fontWeight: '600',
  },
  historySavings: {
    fontSize: 14,
    fontWeight: '700',
  },
  historyFooter: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
    paddingTop: 12,
  },
  historyDate: {
    fontSize: 12,
    fontWeight: '500',
  },
  confirmationModal: {
    width: '90%',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingVertical: 30,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 12,
  },
  
  // DTI Calculator - Multiple Debts Styles
  addDebtSection: {
    marginBottom: 20,
  },
  debtsListContainer: {
    marginTop: 16,
  },
  debtsListTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
  },
  debtCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
  },
  debtInfo: {
    flex: 1,
  },
  debtName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  debtAmount: {
    fontSize: 14,
    fontWeight: '500',
  },
  removeDebtButton: {
    padding: 8,
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeDebtText: {
    fontSize: 18,
    fontWeight: '700',
  },
  totalDebtsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.1)',
  },
  totalDebtsText: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },

  // Fixed DTI Calculator Styles
  debtsContainer: {
    marginBottom: 16,
  },
  debtCardFixed: {
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  debtCardContent: {
    padding: 16,
  },
  debtInfoFixed: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  debtNameFixed: {
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
  },
  debtAmountFixed: {
    fontSize: 16,
    fontWeight: '700',
  },
  removeButtonFixed: {
    width: 32,
    height: 32,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  removeButtonTextFixed: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 18,
  },
  totalDebtsFixed: {
    borderRadius: 16,
    borderWidth: 2,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalLabelFixed: {
    fontSize: 18,
    fontWeight: '700',
  },
  totalAmountFixed: {
    fontSize: 20,
    fontWeight: '800',
  },

  // Amortization Action Buttons
  headerActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButtonSmall: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  actionButtonIcon: {
    fontSize: 16,
    color: '#ffffff',
  },
  compactDebtForm: {
    marginBottom: 20,
  },
  compactDebtInputs: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  compactDebtInputWrapper: {
    flex: 1,
  },
  compactInputLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  compactInputBox: {
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    justifyContent: 'center',
  },
  compactInput: {
    fontSize: 15,
    fontWeight: '600',
  },
  addDebtButtonCompact: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addDebtButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  currentDebtsCompact: {
    marginTop: 16,
  },
  currentDebtsCompactTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  debtsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  debtChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 4,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  debtChipContent: {
    flex: 1,
    marginRight: 8,
  },
  debtChipName: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  debtChipAmount: {
    fontSize: 12,
    fontWeight: '600',
  },
  debtChipRemove: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  debtChipRemoveText: {
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 16,
  },
  totalDebtsCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  totalDebtsCompactLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  totalDebtsCompactAmount: {
    fontSize: 16,
    fontWeight: '800',
  },
  addDebtFormRedesigned: {
    marginBottom: 20,
  },
  debtInputRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  debtInputHalf: {
    flex: 1,
  },
  currentDebtsSection: {
    marginTop: 20,
  },
  currentDebtsTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  debtCardRedesigned: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  debtNameRedesigned: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  debtAmountRedesigned: {
    fontSize: 14,
    fontWeight: '600',
  },
  removeDebtButtonRedesigned: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeDebtTextRedesigned: {
    fontSize: 20,
    fontWeight: '700',
  },
  totalDebtsCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    marginTop: 12,
  },
  totalDebtsLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  totalDebtsAmount: {
    fontSize: 18,
    fontWeight: '800',
  },

  // Combined Amortization Screen Styles
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  addLoanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  addLoanButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  loanSelectionCard: {
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  loanSelectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  loanSelectionName: {
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
  },
  selectionCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  loanSelectionDetails: {
    gap: 4,
  },
  loanSelectionDetail: {
    fontSize: 14,
    fontWeight: '500',
  },
  selectedLoansSection: {
    padding: 20,
    borderRadius: 16,
    margin: 16,
    borderWidth: 1.5,
  },
  selectedLoansText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 16,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 12,
  },

  // Combined Amortization Redesigned Styles
  sectionHeaderRedesigned: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 4,
  },
  pageSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 20,
  },
  quickLoanButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quickLoanButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  loanSelectionCardRedesigned: {
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  emptyStateRedesigned: {
    alignItems: 'center',
    padding: 40,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.02)',
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyStateTextRedesigned: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateDescription: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },

  // New Combined Amortization Screen - Complete Redesign
  amortizationHeaderNew: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    marginBottom: 0,
  },
  loanSelector: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  loanSelectorContent: {
    flex: 1,
  },
  loanSelectorLabel: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  loanSelectorTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  dropdownArrow: {
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  emailButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 64,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  emailButtonIcon: {
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 2,
  },
  emailButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
  dropdownMenu: {
    borderRadius: 12,
    borderWidth: 1,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
  },
  dropdownItemTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 2,
  },
  dropdownItemSubtitle: {
    fontSize: 14,
    fontWeight: '500',
  },
  selectedIndicator: {
    fontSize: 18,
    fontWeight: '700',
  },
  tableHeader: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  monthCellNew: {
    flex: 0.8,
  },
  amortizationTableNew: {
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0,0,0,0.1)',
  },
  tableCell: {
    flex: 1,
    fontSize: 13,
    textAlign: 'center',
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  tableSummary: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderTopWidth: 2,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
  },

  // Empty State for Combined Amortization
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateMessage: {
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
  },

  // DTI Calculator - Single Line Debt Cards
  debtCardSingleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  debtNameSingleLine: {
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 12,
  },
  debtAmountSingleLine: {
    fontSize: 16,
    fontWeight: '700',
    marginRight: 12,
    minWidth: 80,
    textAlign: 'right',
  },
  removeButtonSingleLine: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButtonTextSingleLine: {
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 20,
  },
  totalDebtsSingleLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalLabelSingleLine: {
    fontSize: 16,
    fontWeight: '700',
  },
  totalAmountSingleLine: {
    fontSize: 18,
    fontWeight: '800',
  },

  // DTI Calculator - Completely Redesigned Total Debts Card
  totalDebtsRedesigned: {
    borderRadius: 16,
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  totalDebtsContent: {
    padding: 20,
    alignItems: 'center',
  },
  totalDebtsLabelRedesigned: {
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    opacity: 0.9,
  },
  totalDebtsAmountRedesigned: {
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },

  // Loan Term Section - Completely Redesigned
  loanTermSectionRedesigned: {
    marginBottom: 16,
  },
  termInputRowRedesigned: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  termInputItemRedesigned: {
    flex: 1,
  },
  termInputBoxRedesigned: {
    borderWidth: 1.5,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    height: 52,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
    position: 'relative',
  },
  termInputTextRedesigned: {
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'left',
    paddingLeft: 8,
    color: '#000000', // Force black text for visibility
  },
  termLabelOverlay: {
    position: 'absolute',
    right: 12,
    top: 16,
    fontSize: 12,
    fontWeight: '600',
    opacity: 0.7,
  },
});